-- Seed roles, permissions, default matrix, and site settings. No user passwords.

INSERT OR IGNORE INTO roles (id, slug, name, description, status, created_at, updated_at) VALUES
  ('super_admin', 'super_admin', 'Super Admin', 'Controls the authorization system and the full CMS.', 'active', 1700000000000, 1700000000000),
  ('admin', 'admin', 'Admin', 'Operates the website and CMS. Cannot manage roles or permissions.', 'active', 1700000000000, 1700000000000),
  ('chair', 'chair', 'Chair', 'Leadership oversight, including authorized approval and publishing.', 'active', 1700000000000, 1700000000000),
  ('vice_chair', 'vice_chair', 'Vice Chair', 'Supports chair oversight for authorized content.', 'active', 1700000000000, 1700000000000),
  ('secretary', 'secretary', 'Secretary', 'Creates and edits organisational content. Does not publish by default.', 'active', 1700000000000, 1700000000000),
  ('vice_secretary', 'vice_secretary', 'Vice Secretary', 'Supports the secretary with content creation and editing.', 'active', 1700000000000, 1700000000000),
  ('treasurer', 'treasurer', 'Treasurer', 'Manages public donation and payment information.', 'active', 1700000000000, 1700000000000),
  ('member', 'member', 'Member', 'Limited organisational access and personal account management.', 'active', 1700000000000, 1700000000000);

INSERT OR IGNORE INTO permissions (id, module, action, description) VALUES
  ('pages.view', 'pages', 'view', 'view pages'),
  ('pages.create', 'pages', 'create', 'create pages'),
  ('pages.edit', 'pages', 'edit', 'edit pages'),
  ('pages.delete', 'pages', 'delete', 'delete pages'),
  ('pages.approve', 'pages', 'approve', 'approve pages'),
  ('pages.publish', 'pages', 'publish', 'publish pages'),
  ('programs.view', 'programs', 'view', 'view programs'),
  ('programs.create', 'programs', 'create', 'create programs'),
  ('programs.edit', 'programs', 'edit', 'edit programs'),
  ('programs.delete', 'programs', 'delete', 'delete programs'),
  ('programs.approve', 'programs', 'approve', 'approve programs'),
  ('programs.publish', 'programs', 'publish', 'publish programs'),
  ('projects.view', 'projects', 'view', 'view projects'),
  ('projects.create', 'projects', 'create', 'create projects'),
  ('projects.edit', 'projects', 'edit', 'edit projects'),
  ('projects.delete', 'projects', 'delete', 'delete projects'),
  ('projects.approve', 'projects', 'approve', 'approve projects'),
  ('projects.publish', 'projects', 'publish', 'publish projects'),
  ('stories.view', 'stories', 'view', 'view stories'),
  ('stories.create', 'stories', 'create', 'create stories'),
  ('stories.edit', 'stories', 'edit', 'edit stories'),
  ('stories.delete', 'stories', 'delete', 'delete stories'),
  ('stories.approve', 'stories', 'approve', 'approve stories'),
  ('stories.publish', 'stories', 'publish', 'publish stories'),
  ('news.view', 'news', 'view', 'view news'),
  ('news.create', 'news', 'create', 'create news'),
  ('news.edit', 'news', 'edit', 'edit news'),
  ('news.delete', 'news', 'delete', 'delete news'),
  ('news.approve', 'news', 'approve', 'approve news'),
  ('news.publish', 'news', 'publish', 'publish news'),
  ('events.view', 'events', 'view', 'view events'),
  ('events.create', 'events', 'create', 'create events'),
  ('events.edit', 'events', 'edit', 'edit events'),
  ('events.delete', 'events', 'delete', 'delete events'),
  ('events.approve', 'events', 'approve', 'approve events'),
  ('events.publish', 'events', 'publish', 'publish events'),
  ('media.view', 'media', 'view', 'view media'),
  ('media.create', 'media', 'create', 'create media'),
  ('media.edit', 'media', 'edit', 'edit media'),
  ('media.delete', 'media', 'delete', 'delete media'),
  ('media.approve', 'media', 'approve', 'approve media'),
  ('media.publish', 'media', 'publish', 'publish media'),
  ('impact.view', 'impact', 'view', 'view impact'),
  ('impact.create', 'impact', 'create', 'create impact'),
  ('impact.edit', 'impact', 'edit', 'edit impact'),
  ('impact.delete', 'impact', 'delete', 'delete impact'),
  ('impact.approve', 'impact', 'approve', 'approve impact'),
  ('impact.publish', 'impact', 'publish', 'publish impact'),
  ('organization.view', 'organization', 'view', 'view organization'),
  ('organization.create', 'organization', 'create', 'create organization'),
  ('organization.edit', 'organization', 'edit', 'edit organization'),
  ('organization.delete', 'organization', 'delete', 'delete organization'),
  ('organization.approve', 'organization', 'approve', 'approve organization'),
  ('organization.publish', 'organization', 'publish', 'publish organization'),
  ('donations.view', 'donations', 'view', 'view donations'),
  ('donations.create', 'donations', 'create', 'create donations'),
  ('donations.edit', 'donations', 'edit', 'edit donations'),
  ('donations.delete', 'donations', 'delete', 'delete donations'),
  ('donations.approve', 'donations', 'approve', 'approve donations'),
  ('donations.publish', 'donations', 'publish', 'publish donations'),
  ('users.view', 'users', 'view', 'view users'),
  ('users.create', 'users', 'create', 'create users'),
  ('users.edit', 'users', 'edit', 'edit users'),
  ('users.delete', 'users', 'delete', 'delete users'),
  ('users.approve', 'users', 'approve', 'approve users'),
  ('users.publish', 'users', 'publish', 'publish users'),
  ('settings.view', 'settings', 'view', 'view settings'),
  ('settings.create', 'settings', 'create', 'create settings'),
  ('settings.edit', 'settings', 'edit', 'edit settings'),
  ('settings.delete', 'settings', 'delete', 'delete settings'),
  ('settings.approve', 'settings', 'approve', 'approve settings'),
  ('settings.publish', 'settings', 'publish', 'publish settings'),
  ('audit.view', 'audit', 'view', 'view audit'),
  ('audit.create', 'audit', 'create', 'create audit'),
  ('audit.edit', 'audit', 'edit', 'edit audit'),
  ('audit.delete', 'audit', 'delete', 'delete audit'),
  ('audit.approve', 'audit', 'approve', 'approve audit'),
  ('audit.publish', 'audit', 'publish', 'publish audit'),
  ('roles.view', 'roles', 'view', 'view roles'),
  ('roles.create', 'roles', 'create', 'create roles'),
  ('roles.edit', 'roles', 'edit', 'edit roles'),
  ('roles.delete', 'roles', 'delete', 'delete roles'),
  ('roles.approve', 'roles', 'approve', 'approve roles'),
  ('roles.publish', 'roles', 'publish', 'publish roles'),
  ('maintenance.view', 'maintenance', 'view', 'view maintenance'),
  ('maintenance.create', 'maintenance', 'create', 'create maintenance'),
  ('maintenance.edit', 'maintenance', 'edit', 'edit maintenance'),
  ('maintenance.delete', 'maintenance', 'delete', 'delete maintenance'),
  ('maintenance.approve', 'maintenance', 'approve', 'approve maintenance'),
  ('maintenance.publish', 'maintenance', 'publish', 'publish maintenance'),
  ('privacy.view', 'privacy', 'view', 'view privacy'),
  ('privacy.create', 'privacy', 'create', 'create privacy'),
  ('privacy.edit', 'privacy', 'edit', 'edit privacy'),
  ('privacy.delete', 'privacy', 'delete', 'delete privacy'),
  ('privacy.approve', 'privacy', 'approve', 'approve privacy'),
  ('privacy.publish', 'privacy', 'publish', 'publish privacy');

INSERT OR IGNORE INTO role_permissions (role_id, permission_id) VALUES
  ('super_admin', 'pages.view'),
  ('super_admin', 'pages.create'),
  ('super_admin', 'pages.edit'),
  ('super_admin', 'pages.delete'),
  ('super_admin', 'pages.approve'),
  ('super_admin', 'pages.publish'),
  ('super_admin', 'programs.view'),
  ('super_admin', 'programs.create'),
  ('super_admin', 'programs.edit'),
  ('super_admin', 'programs.delete'),
  ('super_admin', 'programs.approve'),
  ('super_admin', 'programs.publish'),
  ('super_admin', 'projects.view'),
  ('super_admin', 'projects.create'),
  ('super_admin', 'projects.edit'),
  ('super_admin', 'projects.delete'),
  ('super_admin', 'projects.approve'),
  ('super_admin', 'projects.publish'),
  ('super_admin', 'stories.view'),
  ('super_admin', 'stories.create'),
  ('super_admin', 'stories.edit'),
  ('super_admin', 'stories.delete'),
  ('super_admin', 'stories.approve'),
  ('super_admin', 'stories.publish'),
  ('super_admin', 'news.view'),
  ('super_admin', 'news.create'),
  ('super_admin', 'news.edit'),
  ('super_admin', 'news.delete'),
  ('super_admin', 'news.approve'),
  ('super_admin', 'news.publish'),
  ('super_admin', 'events.view'),
  ('super_admin', 'events.create'),
  ('super_admin', 'events.edit'),
  ('super_admin', 'events.delete'),
  ('super_admin', 'events.approve'),
  ('super_admin', 'events.publish'),
  ('super_admin', 'media.view'),
  ('super_admin', 'media.create'),
  ('super_admin', 'media.edit'),
  ('super_admin', 'media.delete'),
  ('super_admin', 'media.approve'),
  ('super_admin', 'media.publish'),
  ('super_admin', 'impact.view'),
  ('super_admin', 'impact.create'),
  ('super_admin', 'impact.edit'),
  ('super_admin', 'impact.delete'),
  ('super_admin', 'impact.approve'),
  ('super_admin', 'impact.publish'),
  ('super_admin', 'organization.view'),
  ('super_admin', 'organization.create'),
  ('super_admin', 'organization.edit'),
  ('super_admin', 'organization.delete'),
  ('super_admin', 'organization.approve'),
  ('super_admin', 'organization.publish'),
  ('super_admin', 'donations.view'),
  ('super_admin', 'donations.create'),
  ('super_admin', 'donations.edit'),
  ('super_admin', 'donations.delete'),
  ('super_admin', 'donations.approve'),
  ('super_admin', 'donations.publish'),
  ('super_admin', 'users.view'),
  ('super_admin', 'users.create'),
  ('super_admin', 'users.edit'),
  ('super_admin', 'users.delete'),
  ('super_admin', 'users.approve'),
  ('super_admin', 'users.publish'),
  ('super_admin', 'settings.view'),
  ('super_admin', 'settings.create'),
  ('super_admin', 'settings.edit'),
  ('super_admin', 'settings.delete'),
  ('super_admin', 'settings.approve'),
  ('super_admin', 'settings.publish'),
  ('super_admin', 'audit.view'),
  ('super_admin', 'audit.create'),
  ('super_admin', 'audit.edit'),
  ('super_admin', 'audit.delete'),
  ('super_admin', 'audit.approve'),
  ('super_admin', 'audit.publish'),
  ('super_admin', 'roles.view'),
  ('super_admin', 'roles.create'),
  ('super_admin', 'roles.edit'),
  ('super_admin', 'roles.delete'),
  ('super_admin', 'roles.approve'),
  ('super_admin', 'roles.publish'),
  ('super_admin', 'maintenance.view'),
  ('super_admin', 'maintenance.create'),
  ('super_admin', 'maintenance.edit'),
  ('super_admin', 'maintenance.delete'),
  ('super_admin', 'maintenance.approve'),
  ('super_admin', 'maintenance.publish'),
  ('super_admin', 'privacy.view'),
  ('super_admin', 'privacy.create'),
  ('super_admin', 'privacy.edit'),
  ('super_admin', 'privacy.delete'),
  ('super_admin', 'privacy.approve'),
  ('super_admin', 'privacy.publish'),
  ('admin', 'pages.view'),
  ('admin', 'pages.create'),
  ('admin', 'pages.edit'),
  ('admin', 'pages.delete'),
  ('admin', 'pages.approve'),
  ('admin', 'pages.publish'),
  ('admin', 'programs.view'),
  ('admin', 'programs.create'),
  ('admin', 'programs.edit'),
  ('admin', 'programs.delete'),
  ('admin', 'programs.approve'),
  ('admin', 'programs.publish'),
  ('admin', 'projects.view'),
  ('admin', 'projects.create'),
  ('admin', 'projects.edit'),
  ('admin', 'projects.delete'),
  ('admin', 'projects.approve'),
  ('admin', 'projects.publish'),
  ('admin', 'stories.view'),
  ('admin', 'stories.create'),
  ('admin', 'stories.edit'),
  ('admin', 'stories.delete'),
  ('admin', 'stories.approve'),
  ('admin', 'stories.publish'),
  ('admin', 'news.view'),
  ('admin', 'news.create'),
  ('admin', 'news.edit'),
  ('admin', 'news.delete'),
  ('admin', 'news.approve'),
  ('admin', 'news.publish'),
  ('admin', 'events.view'),
  ('admin', 'events.create'),
  ('admin', 'events.edit'),
  ('admin', 'events.delete'),
  ('admin', 'events.approve'),
  ('admin', 'events.publish'),
  ('admin', 'media.view'),
  ('admin', 'media.create'),
  ('admin', 'media.edit'),
  ('admin', 'media.delete'),
  ('admin', 'media.approve'),
  ('admin', 'media.publish'),
  ('admin', 'impact.view'),
  ('admin', 'impact.create'),
  ('admin', 'impact.edit'),
  ('admin', 'impact.delete'),
  ('admin', 'impact.approve'),
  ('admin', 'impact.publish'),
  ('admin', 'organization.view'),
  ('admin', 'organization.create'),
  ('admin', 'organization.edit'),
  ('admin', 'organization.delete'),
  ('admin', 'organization.approve'),
  ('admin', 'organization.publish'),
  ('admin', 'donations.view'),
  ('admin', 'donations.create'),
  ('admin', 'donations.edit'),
  ('admin', 'donations.delete'),
  ('admin', 'donations.approve'),
  ('admin', 'donations.publish'),
  ('admin', 'users.view'),
  ('admin', 'users.create'),
  ('admin', 'users.edit'),
  ('admin', 'users.delete'),
  ('admin', 'users.approve'),
  ('admin', 'users.publish'),
  ('admin', 'settings.view'),
  ('admin', 'settings.create'),
  ('admin', 'settings.edit'),
  ('admin', 'settings.delete'),
  ('admin', 'settings.approve'),
  ('admin', 'settings.publish'),
  ('admin', 'audit.view'),
  ('admin', 'audit.create'),
  ('admin', 'audit.edit'),
  ('admin', 'audit.delete'),
  ('admin', 'audit.approve'),
  ('admin', 'audit.publish'),
  ('admin', 'privacy.view'),
  ('admin', 'privacy.create'),
  ('admin', 'privacy.edit'),
  ('admin', 'privacy.delete'),
  ('admin', 'privacy.approve'),
  ('admin', 'privacy.publish'),
  ('chair', 'pages.view'),
  ('chair', 'pages.approve'),
  ('chair', 'pages.publish'),
  ('chair', 'programs.view'),
  ('chair', 'programs.approve'),
  ('chair', 'programs.publish'),
  ('chair', 'projects.view'),
  ('chair', 'projects.approve'),
  ('chair', 'projects.publish'),
  ('chair', 'stories.view'),
  ('chair', 'stories.approve'),
  ('chair', 'stories.publish'),
  ('chair', 'news.view'),
  ('chair', 'news.approve'),
  ('chair', 'news.publish'),
  ('chair', 'events.view'),
  ('chair', 'events.approve'),
  ('chair', 'events.publish'),
  ('chair', 'media.view'),
  ('chair', 'impact.view'),
  ('chair', 'organization.view'),
  ('chair', 'donations.view'),
  ('chair', 'users.view'),
  ('chair', 'settings.view'),
  ('chair', 'audit.view'),
  ('chair', 'privacy.view'),
  ('vice_chair', 'pages.view'),
  ('vice_chair', 'pages.approve'),
  ('vice_chair', 'pages.publish'),
  ('vice_chair', 'programs.view'),
  ('vice_chair', 'programs.approve'),
  ('vice_chair', 'programs.publish'),
  ('vice_chair', 'projects.view'),
  ('vice_chair', 'projects.approve'),
  ('vice_chair', 'projects.publish'),
  ('vice_chair', 'stories.view'),
  ('vice_chair', 'stories.approve'),
  ('vice_chair', 'stories.publish'),
  ('vice_chair', 'news.view'),
  ('vice_chair', 'news.approve'),
  ('vice_chair', 'news.publish'),
  ('vice_chair', 'events.view'),
  ('vice_chair', 'events.approve'),
  ('vice_chair', 'events.publish'),
  ('vice_chair', 'media.view'),
  ('vice_chair', 'impact.view'),
  ('vice_chair', 'organization.view'),
  ('vice_chair', 'donations.view'),
  ('vice_chair', 'settings.view'),
  ('vice_chair', 'privacy.view'),
  ('secretary', 'pages.view'),
  ('secretary', 'pages.create'),
  ('secretary', 'pages.edit'),
  ('secretary', 'programs.view'),
  ('secretary', 'programs.create'),
  ('secretary', 'programs.edit'),
  ('secretary', 'projects.view'),
  ('secretary', 'projects.create'),
  ('secretary', 'projects.edit'),
  ('secretary', 'stories.view'),
  ('secretary', 'stories.create'),
  ('secretary', 'stories.edit'),
  ('secretary', 'news.view'),
  ('secretary', 'news.create'),
  ('secretary', 'news.edit'),
  ('secretary', 'events.view'),
  ('secretary', 'events.create'),
  ('secretary', 'events.edit'),
  ('secretary', 'media.view'),
  ('secretary', 'media.create'),
  ('secretary', 'media.edit'),
  ('secretary', 'impact.view'),
  ('secretary', 'impact.edit'),
  ('secretary', 'organization.view'),
  ('secretary', 'organization.edit'),
  ('secretary', 'donations.view'),
  ('secretary', 'privacy.view'),
  ('secretary', 'privacy.edit'),
  ('vice_secretary', 'pages.view'),
  ('vice_secretary', 'pages.create'),
  ('vice_secretary', 'pages.edit'),
  ('vice_secretary', 'programs.view'),
  ('vice_secretary', 'programs.create'),
  ('vice_secretary', 'programs.edit'),
  ('vice_secretary', 'projects.view'),
  ('vice_secretary', 'projects.create'),
  ('vice_secretary', 'projects.edit'),
  ('vice_secretary', 'stories.view'),
  ('vice_secretary', 'stories.create'),
  ('vice_secretary', 'stories.edit'),
  ('vice_secretary', 'news.view'),
  ('vice_secretary', 'news.create'),
  ('vice_secretary', 'news.edit'),
  ('vice_secretary', 'events.view'),
  ('vice_secretary', 'events.create'),
  ('vice_secretary', 'events.edit'),
  ('vice_secretary', 'media.view'),
  ('vice_secretary', 'media.create'),
  ('vice_secretary', 'media.edit'),
  ('vice_secretary', 'impact.view'),
  ('vice_secretary', 'organization.view'),
  ('vice_secretary', 'donations.view'),
  ('vice_secretary', 'privacy.view'),
  ('treasurer', 'pages.view'),
  ('treasurer', 'programs.view'),
  ('treasurer', 'projects.view'),
  ('treasurer', 'stories.view'),
  ('treasurer', 'news.view'),
  ('treasurer', 'events.view'),
  ('treasurer', 'media.view'),
  ('treasurer', 'impact.view'),
  ('treasurer', 'organization.view'),
  ('treasurer', 'donations.view'),
  ('treasurer', 'donations.create'),
  ('treasurer', 'donations.edit'),
  ('treasurer', 'donations.approve'),
  ('treasurer', 'donations.publish'),
  ('treasurer', 'privacy.view');

INSERT OR IGNORE INTO site_settings (key, value, updated_by, updated_at) VALUES ('organization', '{"name":"Nazarene for She","description":"Nazarene for She (NS) is a community-based organisation in Congo, Kawangware, Nairobi County. It empowers young girls through sanitary pads, vocational skills, and economic opportunity.","mission":"Empowering young girls through provision of sanitary pads and economic empowerment of school dropouts.","vision":"To create a self-sustaining generation of young women.","values":["Dignity","Knowledge","Faith","Community","Skill","Integrity"],"email":"nazareneforshe@gmail.com","phone":"","location":"Congo, Kawangware, Nairobi County, Kenya.","postalAddress":"P.O. Box 20025-00200 Nairobi, Kenya","social":{"instagram":"","facebook":"","linkedin":"","youtube":"","tiktok":""}}', NULL, 1700000000000);

INSERT OR IGNORE INTO site_settings (key, value, updated_by, updated_at) VALUES ('donations', '{"intro":"Your contribution can help provide practical support today while helping build sustainable opportunities for tomorrow.","methods":[],"note":"Official payment details are published only when the organisation confirms them."}', NULL, 1700000000000);

INSERT OR IGNORE INTO site_settings (key, value, updated_by, updated_at) VALUES ('seo_defaults', '{"title":"Nazarene for She — She Empowered, Community Inspired.","description":"Nazarene for She helps girls and young women in Kawangware, Nairobi, overcome period poverty, stay in school, gain practical skills, and move toward self-sustaining futures."}', NULL, 1700000000000);

INSERT OR IGNORE INTO site_settings (key, value, updated_by, updated_at) VALUES ('privacy_policy', '{"title":"Privacy","body":"<p>This policy covers the public website. Contact, donation-inquiry and atelier request forms may collect your name, email, optional phone number, organisation, garment preferences, and a message. We use that information to respond to your inquiry.</p><p>We do not sell personal data. We do not publish beneficiary identities without consent.</p>"}', NULL, 1700000000000);

INSERT OR IGNORE INTO site_settings (key, value, updated_by, updated_at) VALUES ('maintenance', '{"enabled":false,"status":"completed","title":"We will be back shortly","message":"The website is temporarily unavailable while we carry out scheduled work.","estimatedReturnAt":null,"contact":"nazareneforshe@gmail.com","startAt":null,"endAt":null}', NULL, 1700000000000);

INSERT OR IGNORE INTO site_settings (key, value, updated_by, updated_at) VALUES ('privacy_settings', '{"auditRetentionDays":365,"cookieConsentRequired":false}', NULL, 1700000000000);

INSERT OR IGNORE INTO impact_statistics (id, label, value, status, note, sort_order, published, updated_at) VALUES
  ('girls-supported', 'Girls currently supported', '600+', 'verified', 'Verified organisational figure.', 1, 1, 1700000000000),
  ('girls-reached', 'Girls reached', '—', 'awaiting-verification', '', 2, 1, 1700000000000),
  ('dignity-kits', 'Dignity kits distributed', '—', 'awaiting-verification', '', 3, 1, 1700000000000),
  ('mentorship-sessions', 'Mentorship sessions', '—', 'awaiting-verification', '', 4, 1, 1700000000000),
  ('health-sessions', 'Menstrual health sessions', '—', 'awaiting-verification', '', 5, 1, 1700000000000),
  ('vocational-trainees', 'Vocational trainees', '—', 'awaiting-verification', '', 6, 1, 1700000000000),
  ('entrepreneurship', 'Entrepreneurship beneficiaries', '—', 'awaiting-verification', '', 7, 1, 1700000000000),
  ('partners', 'Community partners', '—', 'awaiting-verification', '', 8, 1, 1700000000000);
