-- Align CMS modules with this public site: drop Projects and News, add The Atelier, seed real site pages.
PRAGMA foreign_keys = ON;

INSERT OR IGNORE INTO permissions (id, module, action, description) VALUES
  ('atelier.view', 'atelier', 'view', 'view atelier'),
  ('atelier.create', 'atelier', 'create', 'create atelier'),
  ('atelier.edit', 'atelier', 'edit', 'edit atelier'),
  ('atelier.delete', 'atelier', 'delete', 'delete atelier'),
  ('atelier.approve', 'atelier', 'approve', 'approve atelier'),
  ('atelier.publish', 'atelier', 'publish', 'publish atelier');

-- Copy each role's Programs access onto The Atelier so existing databases keep the same RBAC shape.
INSERT OR IGNORE INTO role_permissions (role_id, permission_id)
SELECT rp.role_id, 'atelier.' || substr(rp.permission_id, 10)
FROM role_permissions rp
WHERE rp.permission_id LIKE 'programs.%';

DELETE FROM role_permissions WHERE permission_id LIKE 'projects.%' OR permission_id LIKE 'news.%';
DELETE FROM permissions WHERE module IN ('projects', 'news');

UPDATE content_items SET deleted_at = 1756800000000, updated_at = 1756800000000
WHERE type IN ('projects', 'news') AND deleted_at IS NULL;

INSERT OR IGNORE INTO content_items (
  id, type, title, slug, excerpt, content, featured_image, status, payload,
  seo_title, seo_description, canonical_url, og_title, og_description, og_image,
  created_by, updated_by, created_at, updated_at, published_at, deleted_at
) VALUES
  ('page-about', 'pages', 'She is not a problem to be solved.', 'about', 'She is a person with potential who deserves opportunity. This page is for visitors who want the deeper organisational picture. The story itself lives on the journey through our work.', '', '', 'published', '{"path":"/about"}', 'She is not a problem to be solved.', 'She is a person with potential who deserves opportunity. This page is for visitors who want the deeper organisational picture. The story itself lives on the journey through our work.', '/about', '', '', '', NULL, NULL, 1756800000000, 1756800000000, 1756800000000, NULL),
  ('page-get-involved', 'pages', 'There are many ways to walk with her. Pick the one that is yours.', 'get-involved', 'Help remove a barrier between her and her future. Whether you give, teach, pray or partner, you are participating in a transformation system — not a one-time rescue.', '', '', 'published', '{"path":"/get-involved"}', 'There are many ways to walk with her. Pick the one that is yours.', 'Help remove a barrier between her and her future. Whether you give, teach, pray or partner, you are participating in a transformation system — not a one-time rescue.', '/get-involved', '', '', '', NULL, NULL, 1756800000000, 1756800000000, 1756800000000, NULL),
  ('page-partnership', 'pages', 'You are not simply funding a program.', 'partnership', 'You are helping build pathways to dignity, skills and independence.', '', '', 'published', '{"path":"/partnership"}', 'You are not simply funding a program.', 'You are helping build pathways to dignity, skills and independence.', '/partnership', '', '', '', NULL, NULL, 1756800000000, 1756800000000, 1756800000000, NULL),
  ('page-terms', 'pages', 'Use this site to understand the work — and to walk with it honestly.', 'terms', 'These terms cover the public website and its forms.', '<h2>Content</h2><p>Unpublished payment details and placeholder stories are marked as such. Do not treat placeholders as official organisational commitments. Mission and vision on this site follow the January 2021 constitution.</p><h2>Giving</h2><p>Donations should be made only through official details published by the organisation. If a field still reads as a placeholder, wait for confirmation before sending funds.</p><h2>The Atelier</h2><p>Requests for garments are inquiries, not completed sales. A price, making time and official payment details will be confirmed in a reply before you should send money. Atmosphere photographs show the workshop, not a specific finished piece already for sale.</p><h2>Stories</h2><p>Photographs used as atmosphere are not portraits of named beneficiaries. Published personal stories will appear only with consent.</p>', '', 'published', '{"path":"/terms"}', 'Use this site to understand the work — and to walk with it honestly.', 'These terms cover the public website and its forms.', '/terms', '', '', '', NULL, NULL, 1756800000000, 1756800000000, 1756800000000, NULL);

INSERT OR IGNORE INTO content_items (
  id, type, title, slug, excerpt, content, featured_image, status, payload,
  seo_title, seo_description, canonical_url, og_title, og_description, og_image,
  created_by, updated_by, created_at, updated_at, published_at, deleted_at
) VALUES
  ('atelier-dress', 'atelier', 'Dresses', 'dress', 'A dress cut and sewn in the workshop — work she can name as her own.', 'Dresses are made to order from the Kawangware atelier. A picture of the finished piece, and a fair price, come when the workshop confirms your request.', '', 'published', '{"collection":"wear","eyebrow":"Made to order","verb":"Cut","lure":"When she finishes a dress, it is not charity leaving the table. It is a girl paid.","sizing":"body"}', 'Dresses', 'A dress cut and sewn in the workshop — work she can name as her own.', '/shop/dress', '', '', '', NULL, NULL, 1756800000000, 1756800000000, 1756800000000, NULL),
  ('atelier-skirt', 'atelier', 'Skirts', 'skirt', 'A skirt from the same tables where she learned the machine.', 'Skirts are sewn as training becomes livelihood. Choose a fit, and wait for the workshop to confirm cloth, timeline and price before any money moves.', '', 'published', '{"collection":"wear","eyebrow":"Made to order","verb":"Drape","lure":"A skirt she draped is a skill you can wear — and a wage she can keep.","sizing":"body"}', 'Skirts', 'A skirt from the same tables where she learned the machine.', '/shop/skirt', '', '', '', NULL, NULL, 1756800000000, 1756800000000, 1756800000000, NULL),
  ('atelier-blouse', 'atelier', 'Blouses', 'blouse', 'A blouse finished by hands that are learning a trade.', 'Blouses are part of dressmaking practice. Your request is an order conversation with the organisation — not a card checkout, and not a claim that a specific garment is already on a hanger.', '', 'published', '{"collection":"wear","eyebrow":"Made to order","verb":"Stitch","lure":"Every stitch on a blouse is practice that can become independence.","sizing":"body"}', 'Blouses', 'A blouse finished by hands that are learning a trade.', '/shop/blouse', '', '', '', NULL, NULL, 1756800000000, 1756800000000, 1756800000000, NULL),
  ('atelier-palazzo', 'atelier', 'Palazzos', 'palazzo', 'Wide-leg palazzos cut so a girl can sell the ease she sewed.', 'Palazzos are made to order in the workshop. Tell us a cloth and a fit. The team will confirm what they can take on — and the price — before you pay.', '', 'published', '{"collection":"wear","eyebrow":"Made to order","verb":"Flow","lure":"Palazzos she made can walk out of Kawangware as her work, sold.","sizing":"body"}', 'Palazzos', 'Wide-leg palazzos cut so a girl can sell the ease she sewed.', '/shop/palazzo', '', '', '', NULL, NULL, 1756800000000, 1756800000000, 1756800000000, NULL),
  ('atelier-kimono', 'atelier', 'Kimonos', 'kimono', 'A kimono wrapped from the same cloth she is learning to honour.', 'Kimonos and wraps are sewn to order. Choose a cloth on the table, then wait for the workshop to answer with timeline and price.', '', 'published', '{"collection":"wear","eyebrow":"Made to order","verb":"Wrap","lure":"Wrap yourself in her craft. Let the payment wrap around her future.","sizing":"body"}', 'Kimonos', 'A kimono wrapped from the same cloth she is learning to honour.', '/shop/kimono', '', '', '', NULL, NULL, 1756800000000, 1756800000000, 1756800000000, NULL),
  ('atelier-crop-top', 'atelier', 'Crop tops', 'crop-top', 'A crop top finished on the machines where she is becoming a tailor.', 'Crop tops are made to order as part of dressmaking practice. Choose a fit and a cloth. Price is confirmed before any money moves.', '', 'published', '{"collection":"wear","eyebrow":"Made to order","verb":"Crop","lure":"Small piece. Real wage. The girl who cropped it is the one you are paying.","sizing":"body"}', 'Crop tops', 'A crop top finished on the machines where she is becoming a tailor.', '/shop/crop-top', '', '', '', NULL, NULL, 1756800000000, 1756800000000, 1756800000000, NULL),
  ('atelier-jumpsuit', 'atelier', 'Jumpsuits', 'jumpsuit', 'A jumpsuit joined at the same seam she is learning to trust.', 'Jumpsuits are a fuller make: cut, fit and finish. Request one and the workshop will say what they can sew, when, and for how much, before you pay.', '', 'published', '{"collection":"wear","eyebrow":"Made to order","verb":"Join","lure":"One garment, many skills — cutting, fitting, finishing. Buying it pays all of them.","sizing":"body"}', 'Jumpsuits', 'A jumpsuit joined at the same seam she is learning to trust.', '/shop/jumpsuit', '', '', '', NULL, NULL, 1756800000000, 1756800000000, 1756800000000, NULL),
  ('atelier-uniform', 'atelier', 'Uniforms', 'uniform', 'A uniform sewn so a girl can be paid for work that looks like dignity.', 'Uniforms are made to order in the Kawangware workshop as part of vocational training. Tell us who will wear it and a size. The organisation confirms cloth, timeline and price before you pay.', '', 'published', '{"collection":"day","eyebrow":"Made to order","verb":"Stand","lure":"A uniform she sewed can dress a working day — and fund hers.","sizing":"body"}', 'Uniforms', 'A uniform sewn so a girl can be paid for work that looks like dignity.', '/shop/uniform', '', '', '', NULL, NULL, 1756800000000, 1756800000000, 1756800000000, NULL),
  ('atelier-trouser', 'atelier', 'Trousers', 'trouser', 'Trousers tailored on the tables where she is building a trade.', 'Trousers are sewn to order. Choose a fit, note a cloth, and wait for the workshop to confirm price and making time.', '', 'published', '{"collection":"day","eyebrow":"Made to order","verb":"Tailor","lure":"Trousers she tailored are not a favour. They are a girl earning from skill.","sizing":"body"}', 'Trousers', 'Trousers tailored on the tables where she is building a trade.', '/shop/trouser', '', '', '', NULL, NULL, 1756800000000, 1756800000000, 1756800000000, NULL),
  ('atelier-jacket', 'atelier', 'Jackets', 'jacket', 'A jacket lined by hands that are learning structure, not only style.', 'Jackets are a longer make. Request one and the workshop will answer with what they can take on, a timeline, and a fair price before you pay.', '', 'published', '{"collection":"day","eyebrow":"Made to order","verb":"Line","lure":"A jacket takes time. Paying for that time is how training becomes income.","sizing":"body"}', 'Jackets', 'A jacket lined by hands that are learning structure, not only style.', '/shop/jacket', '', '', '', NULL, NULL, 1756800000000, 1756800000000, 1756800000000, NULL),
  ('atelier-sweater', 'atelier', 'Sweaters', 'sweater', 'A sweater finished so her warmth can also be her wage.', 'Sweaters are made to order in the workshop. Choose a size and a cloth preference. Price is confirmed in the reply, not on this page.', '', 'published', '{"collection":"day","eyebrow":"Made to order","verb":"Warm","lure":"Wear the warmth she made. Let the payment stay with her.","sizing":"body"}', 'Sweaters', 'A sweater finished so her warmth can also be her wage.', '/shop/sweater', '', '', '', NULL, NULL, 1756800000000, 1756800000000, 1756800000000, NULL),
  ('atelier-tote', 'atelier', 'Tote bags', 'tote', 'A tote bag she carried through every step — cut, stitch, finish.', 'Tote bags are sewn in the Kawangware atelier as part of vocational training. They are made to order. A fair price comes when the workshop confirms your request.', '', 'published', '{"collection":"carry","eyebrow":"Made to order","verb":"Carry","lure":"Carry her work on your shoulder. That weight is a girl''s income.","sizing":"one"}', 'Tote bags', 'A tote bag she carried through every step — cut, stitch, finish.', '/shop/tote', '', '', '', NULL, NULL, 1756800000000, 1756800000000, 1756800000000, NULL),
  ('atelier-kitenge', 'atelier', 'Kitenges', 'kitenge', 'A kitenge wrapped from cloth she is learning to cut with care.', 'Kitenges are cut and finished to order. Choose a cloth on the table, tell us how it should live, and wait for the workshop to confirm price and timing.', '', 'published', '{"collection":"carry","eyebrow":"Made to order","verb":"Wrap","lure":"A kitenge is cloth with a life in it. Buying one pays the girl who finished it.","sizing":"one"}', 'Kitenges', 'A kitenge wrapped from cloth she is learning to cut with care.', '/shop/kitenge', '', '', '', NULL, NULL, 1756800000000, 1756800000000, 1756800000000, NULL),
  ('atelier-cap', 'atelier', 'Caps', 'cap', 'A cap finished by a girl whose skill is becoming a livelihood.', 'Caps are made to order in the workshop. Choose one, note a cloth, and the organisation will reply with a fair price before any money moves.', '', 'published', '{"collection":"carry","eyebrow":"Made to order","verb":"Crown","lure":"A small crown. A real wage. Choosing it means you are paying her — not speaking for her.","sizing":"one"}', 'Caps', 'A cap finished by a girl whose skill is becoming a livelihood.', '/shop/cap', '', '', '', NULL, NULL, 1756800000000, 1756800000000, 1756800000000, NULL);

