import {
  allPermissionKeys,
  type PermissionKey,
  type RoleSlug,
} from "./permissions.ts";

const ALL = allPermissionKeys();

function except(keys: PermissionKey[], denied: string[]) {
  return keys.filter((key) => !denied.some((prefix) => key === prefix || key.startsWith(prefix)));
}

export const DEFAULT_ROLE_PERMISSIONS = {
  super_admin: ALL,
  admin: except(ALL, ["roles.", "maintenance."]),
  chair: [
    "pages.view",
    "pages.approve",
    "pages.publish",
    "programs.view",
    "programs.approve",
    "programs.publish",
    "stories.view",
    "stories.approve",
    "stories.publish",
    "events.view",
    "events.approve",
    "events.publish",
    "atelier.view",
    "atelier.approve",
    "atelier.publish",
    "media.view",
    "impact.view",
    "organization.view",
    "donations.view",
    "users.view",
    "settings.view",
    "audit.view",
    "privacy.view",
  ],
  vice_chair: [
    "pages.view",
    "pages.approve",
    "pages.publish",
    "programs.view",
    "programs.approve",
    "programs.publish",
    "stories.view",
    "stories.approve",
    "stories.publish",
    "events.view",
    "events.approve",
    "events.publish",
    "atelier.view",
    "atelier.approve",
    "atelier.publish",
    "media.view",
    "impact.view",
    "organization.view",
    "donations.view",
    "settings.view",
    "privacy.view",
  ],
  secretary: [
    "pages.view",
    "pages.create",
    "pages.edit",
    "programs.view",
    "programs.create",
    "programs.edit",
    "stories.view",
    "stories.create",
    "stories.edit",
    "events.view",
    "events.create",
    "events.edit",
    "atelier.view",
    "atelier.create",
    "atelier.edit",
    "media.view",
    "media.create",
    "media.edit",
    "impact.view",
    "impact.edit",
    "organization.view",
    "organization.edit",
    "donations.view",
    "privacy.view",
    "privacy.edit",
  ],
  vice_secretary: [
    "pages.view",
    "pages.create",
    "pages.edit",
    "programs.view",
    "programs.create",
    "programs.edit",
    "stories.view",
    "stories.create",
    "stories.edit",
    "events.view",
    "events.create",
    "events.edit",
    "atelier.view",
    "atelier.create",
    "atelier.edit",
    "media.view",
    "media.create",
    "media.edit",
    "impact.view",
    "organization.view",
    "donations.view",
    "privacy.view",
  ],
  treasurer: [
    "pages.view",
    "programs.view",
    "stories.view",
    "events.view",
    "atelier.view",
    "media.view",
    "impact.view",
    "organization.view",
    "donations.view",
    "donations.create",
    "donations.edit",
    "donations.approve",
    "donations.publish",
    "privacy.view",
  ],
  member: [],
} satisfies Record<RoleSlug, PermissionKey[]>;

export const ROLE_DESCRIPTIONS: Record<RoleSlug, string> = {
  super_admin: "Controls the authorization system and the full CMS.",
  admin: "Operates the website and CMS. Cannot manage roles or permissions.",
  chair: "Leadership oversight, including authorized approval and publishing.",
  vice_chair: "Supports chair oversight for authorized content.",
  secretary: "Creates and edits organisational content. Does not publish by default.",
  vice_secretary: "Supports the secretary with content creation and editing.",
  treasurer: "Manages public donation and payment information.",
  member: "Limited organisational access and personal account management.",
};
